name: tembakul_mobile
description: Tembakul Apps.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.4
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  file_picker: ^5.0.1
  mime: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
